DATA_ROOT = '/Users/wushaohua/my/workplace/ailearn/hm/aicompetition/data/'
PUBG_PATH = DATA_ROOT + 'hm/ml/pubg/'
PUBG_SOURCE_PATH = PUBG_PATH + 'source/'
PUBG_SMALL_PATH = PUBG_PATH + 'small/'
PUBG_TRAIN_PATH = PUBG_PATH + 'train/'

PUBG_TRAIN_NAME = 'train_V2.csv'
PUBG_TEST_NAME = 'small_test_V2.csv'

# 源文件
# USE_TRAIN_PATH = PUBG_SOURCE_PATH + PUBG_TRAIN_NAME
# USE_TEST_PATH = PUBG_SOURCE_PATH + PUBG_TEST_NAME
# small文件
USE_TRAIN_PATH = PUBG_SMALL_PATH + PUBG_TRAIN_NAME
USE_TEST_PATH = PUBG_SMALL_PATH + PUBG_TEST_NAME

# train文件
FEATURE_TRAIN_PATH = PUBG_TRAIN_PATH + PUBG_TRAIN_NAME
# USE_TEST_PATH = PUBG_TRAIN_PATH + PUBG_TEST_NAME